name: neom_mates
description: Mate Profile Details for Open Neom.
version: 2.0.0
homepage: https://github.com/Cyberneom/neom_mates
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Cyberneom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git
  neom_profile:
    git:
      url: git@github.com:Cyberneom/neom_profile.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
